config/routes.rb
Rails.application.routes.draw do
  resources :keywords
  resources :entities
  resources :intents
  resources :posts
  resources :homes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/intent.rb
class Intent < ApplicationRecord
end

app/controllers/intents_controller.rb
class IntentsController < ApplicationController
  before_action :set_intent, only: [:show, :edit, :update, :destroy]

  # GET /intents
  # GET /intents.json
  def index
    @intents = Intent.all
  end

  # GET /intents/1
  # GET /intents/1.json
  def show
  end

  # GET /intents/new
  def new
    @intent = Intent.new
  end

  # GET /intents/1/edit
  def edit
  end

  # POST /intents
  # POST /intents.json
  def create
    @intent = Intent.new(intent_params)

    respond_to do |format|
      if @intent.save
        format.html { redirect_to @intent, notice: 'Intent was successfully created.' }
        format.json { render :show, status: :created, location: @intent }
      else
        format.html { render :new }
        format.json { render json: @intent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /intents/1
  # PATCH/PUT /intents/1.json
  def update
    respond_to do |format|
      if @intent.update(intent_params)
        format.html { redirect_to @intent, notice: 'Intent was successfully updated.' }
        format.json { render :show, status: :ok, location: @intent }
      else
        format.html { render :edit }
        format.json { render json: @intent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intents/1
  # DELETE /intents/1.json
  def destroy
    @intent.destroy
    respond_to do |format|
      format.html { redirect_to intents_url, notice: 'Intent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intent
      @intent = Intent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intent_params
      params.require(:intent).permit(:intent)
    end
end

app/helpers/intents_helper.rb
module IntentsHelper
end

app/views/intents/_form.html.erb
<%= form_with(model: intent, local: true) do |form| %>
  <% if intent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intent.errors.count, "error") %> prohibited this intent from being saved:</h2>

      <ul>
        <% intent.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :intent %>
    <%= form.text_field :intent %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/intents/edit.html.erb
<h1>Editing Intent</h1>

<%= render 'form', intent: @intent %>

<%= link_to 'Show', @intent %> |
<%= link_to 'Back', intents_path %>

app/views/intents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Intents</h1>

<table>
  <thead>
    <tr>
      <th>Intent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @intents.each do |intent| %>
      <tr>
        <td><%= intent.intent %></td>
        <td><%= link_to 'Show', intent %></td>
        <td><%= link_to 'Edit', edit_intent_path(intent) %></td>
        <td><%= link_to 'Destroy', intent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intent', new_intent_path %>

app/views/intents/new.html.erb
<h1>New Intent</h1>

<%= render 'form', intent: @intent %>

<%= link_to 'Back', intents_path %>

app/views/intents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Intent:</strong>
  <%= @intent.intent %>
</p>

<%= link_to 'Edit', edit_intent_path(@intent) %> |
<%= link_to 'Back', intents_path %>