config/routes.rb
Rails.application.routes.draw do
  resources :keywords
  resources :entities
  resources :intents
  resources :posts
  resources :homes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/keyword.rb
class Keyword < ApplicationRecord
end

app/controllers/keywords_controller.rb
require 'WitC'
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    # client = Wit.new(access_token: "DGNYYT25FGVUN3OCCNRP52733RPI5W5A")
    #
    # key = Keyword.all
    # # key.each do |k|
    # #
    # #   data={"keyword": k.keyword.to_s, "synonyms": k.synonyms.to_s}
    # #
    # #   client.post_entities_keywords(k.entity, data)
    # #end
    #   data={"keyword": "ha noi",
    #         "synonyms": ["hn"]}
    #
    #   client.post_entities_keywords("address", data)
    #

    obj = WITC.new

    # calling method using object
    obj.create_keyword(params[:key],params[:syn])
    @keywords = Keyword.all

  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def keyword_params
      params.require(:keyword).permit(:keyword, :synonyms, :entity)
    end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_with(model: keyword, local: true) do |form| %>
  <% if keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
        <% keyword.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :keyword %>
    <%= form.text_field :keyword %>
  </div>

  <div class="field">
    <%= form.label :synonyms %>
    <%= form.text_field :synonyms %>
  </div>

  <div class="field">
    <%= form.label :entity %>
    <%= form.text_field :entity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing Keyword</h1>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Keywords</h1>

<table>
  <thead>
    <tr>
      <th>Keyword</th>
      <th>Synonyms</th>
      <th>Entity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.keyword %></td>
        <td><%= keyword.synonyms %></td>
        <td><%= keyword.entity %></td>
        <td><%= link_to 'Show', keyword %></td>
        <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
        <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New Keyword</h1>

<%= render 'form', keyword: @keyword %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @keyword.keyword %>
</p>

<p>
  <strong>Synonyms:</strong>
  <%= @keyword.synonyms %>
</p>

<p>
  <strong>Entity:</strong>
  <%= @keyword.entity %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>